version: "3.9"

services:
  db:
    image: postgres:16.2
    container_name: postgres
    restart: always
    environment:
     - POSTGRES_USER=hello_fastapi
     - POSTGRES_PASSWORD=hello_fastapi
     - POSTGRES_DB=hello_fastapi_dev
    ports:
     - "5432:5432"
    volumes:
     - ./data:/var/lib/postgresql/data

  python:
    build: ./python
    container_name: fastapi
    restart: always
    ports:
      - "8002:8002"
    depends_on:
      - db
    volumes:
      - .:/python/app
    command: ["uvicorn", "app.main:app", "--reload", "--workers", "1", "--host", "0.0.0.0", "--port", "8002"]

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '80:3000'
    volumes:
      - ./frontend:/frontend
    stdin_open: true
    tty: true

  pgadmin:
    image: dpage/pgadmin4:8.5
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: 123456
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db

  go:
    build: ./go
    ports:
      - "8080:8080"
    volumes:
      - ./go:/app


networks:
  default:
      name: hello_fastapi

volumes:
  pgadmin:
